### ISSUE TITLE
KeyError: 'flow_token' in flow2

### ISSUE THREAD

**Issue by lowweihong** [Sinkmanu/TwitterAccountBlocker#1]
Hi, Thanks for this repo & your article! 

I was trying to run the code but it returned me the following error:
```
[*] Js with Bearer token: https://abs.twimg.com/responsive-web/client-web-legacy/main.f0a5ca6a.js
[*] Guest token: 1603035398514483200
[*] Bearer: AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA
[*] rt_url: 3fODegwhTIkaB9ZujUu2Uw
{"flow_token":"g;167102839867201774:-1671028398680:mwkW3JxfEwqerW5Lqs2qSqpA:0","status":"success","subtasks":[{"subtask_id":"LoginJsInstrumentationSubtask","js_instrumentation":{"url":"https://twitter.com/i/js_inst?c_name=ui_metrics","timeout_ms":2000,"next_link":{"link_type":"task","link_id":"next_link"}}}]}
[*] flow_token: g;167102839867201774:-1671028398680:mwkW3JxfEwqerW5Lqs2qSqpA:0
Traceback (most recent call last):
  File "/Users/xxx/Downloads/TwitterAccountBlocker.py", line 165, in <module>
    auth_token = login(authorization_bearer, guest_token, args.username, password, args.email)
  File "/Users/xxx/Downloads/TwitterAccountBlocker.py", line 58, in login
    flow_token = json.loads(r.text)['flow_token']
KeyError: 'flow_token'
```

Here is the response in flow2.
```
{'errors': [{'code': 366, 'message': 'Invalid ATT for the flow'}]}
```

Is it possible for me to get some guidance from you on how to resolve this?

Thanks a millions!

**Comment by Sinkmanu** [comment]
Hi, Twitter is doing a lot of changes in these days.

They have added a cookie called "att" in the login flow and a new mandatory parameter in the URL for retweets.

I have fixed it and uploaded the new code. Perform a pull and test it. 567cf7ccd1428f3be40d9c5b681b4aa5f2480aac

Thanks

**Comment by lowweihong** [comment]
Thanks @Sinkmanu for your fastest response! This is a great help for me. Would you have a patron account or some sort of way I could send my token of appreciation with? Thanks again!

**Comment by Sinkmanu** [comment]
Thanks @lowweihong ! I have in my website (in "whoami" section) a way to do it. Anyway I do it for fun and for contribute to Internet. :)

**Comment by samknp** [comment]
Thanks a lot !
