### ISSUE TITLE
KeyError: 'flow_token' from flow#2

### ISSUE THREAD

**Issue by KeXin95** [Sinkmanu/TwitterAccountBlocker#2]
Hi Sinkmanu,

Thanks for creating this repo! I have been using this script and it works perfectly well all this while. However, this morning I got this issue when trying to run the script.

```
[*] Js with Bearer token: https://abs.twimg.com/responsive-web/client-web-legacy/main.87b695ea.js
[*] Guest token: 1608295472380403713
[*] Bearer: AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA
[*] rt_url: pqzkjauuADyqfbBODfDv_w
[*] flow_token: g;167228249738178608:-1672282497427:AXuOh4k0Bj63KHfkOTugjMhI:0
{'errors': [{'message': 'Over capacity', 'code': 130}]}
Traceback (most recent call last):
  File "TwitterAccountBlocker.py", line 168, in <module>
    auth_token = login(authorization_bearer, guest_token, args.username, password, args.email)
  File "TwitterAccountBlocker.py", line 59, in login
    flow_token = json.loads(r.text)['flow_token']
KeyError: 'flow_token'
```

Note: Here is the print statement i added in flow2:
<img width="951" alt="Screenshot 2022-12-29 at 11 05 22 AM" src="https://user-images.githubusercontent.com/29350673/209898197-8ac48c29-3c10-49d5-ba4c-04f3c0695800.png">

And the print result showed:
```
{'errors': [{'message': 'Over capacity', 'code': 130}]}
```

May I get some pointer from you on how to resolve this issue? 

Thanks so much!

**Comment by Sinkmanu** [comment]
Hi, 

You are welcome.

I have just checked and it is working properly. The error `{'errors': [{'message': 'Over capacity', 'code': 130}]}` is an internal error that means that Twitter is temporarily over capacity. Could you try again?


Regards

**Comment by KeXin95** [comment]
Hi Sinkmanu,

Yup! it works now! Thanks so much for your quick response!
